version: '3.8'
services:
  db:
    container_name: pgdb
    image: postgres
    command: ["postgres", "-c", "listen_addresses=*"]
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  jupyter:
    container_name: notebook
    image: jupyter/minimal-notebook
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: >
      bash -c "pip install -r /home/jovyan/work/notebooks/requirements.txt && 
      jupyter notebook --notebook-dir=/home/jovyan/work/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"

  load-data:
    build: . 
    depends_on:
      - db
    command: ["./wait-for.sh", "pgdb:5432", "--", "python", "./load-data.py"]

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - 9002:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001
  data-loader:
    build: .
    depends_on:
      - minio
    command: ["./wait-for.sh", "minio:9000", "--", "./load-track-data.sh"]
    volumes:
      - minio_data:/data
volumes:
  minio_data:
